name: 'Notify Deployment'
description: 'Send email notifications about deployment status'
author: 'Your Name'

inputs:
  environment:
    description: 'Deployment environment (dev, staging, prod)'
    required: true
  status:
    description: 'Deployment status (success, failure)'
    required: true
  deployment-url:
    description: 'URL of the deployed application'
    required: false
    default: ''
  repository-name:
    description: 'Repository name (auto-detected if not provided)'
    required: false
    default: ''
  additional-info:
    description: 'Additional information to include in notification'
    required: false
    default: ''

runs:
  using: 'node20'

  main: '../../src/index.js'
