name: 'Notify Deployment'
description: 'Send notifications about deployment status to Teams or Email'
author: 'Your Name'

inputs:
  notification-type:
    description: 'Type of notification (teams, email, all)'
    required: true
    default: 'teams'
  webhook-url:
    description: 'Webhook URL for Teams'
    required: false
    default: ''
  email-to:
    description: 'Email address to send notification to'
    required: false
    default: ''
  email-from:
    description: 'Email address to send notification from'
    required: false
    default: 'noreply@azure-deployments.com'
  smtp-server:
    description: 'SMTP server for sending emails'
    required: false
    default: ''
  smtp-port:
    description: 'SMTP port'
    required: false
    default: '587'
  smtp-username:
    description: 'SMTP username'
    required: false
    default: ''
  smtp-password:
    description: 'SMTP password'
    required: false
    default: ''
  environment:
    description: 'Deployment environment'
    required: true
  status:
    description: 'Deployment status (success, failure)'
    required: true
  deployment-url:
    description: 'URL of the deployed application'
    required: false
    default: ''
  app-name:
    description: 'Name of the deployed application'
    required: true
  additional-info:
    description: 'Additional information to include in notification'
    required: false
    default: ''

runs:
  using: 'node20'

  main: '../../src/index.js'
