# ============================================
# EJEMPLO: Azure Function Deployment Workflow
# ============================================
# 📋 INSTRUCCIONES:
# 1. Copia este archivo a: .github/workflows/deploy.yml en tu proyecto
# 2. Reemplaza los valores marcados con ⚠️ CAMBIAR
# 3. Ajusta las ramas según tu estrategia (develop/staging/main)
# 4. ¡Listo! No necesitas configurar secretos (están centralizados)

name: Deploy Azure Function

on:
  push:
    branches:
      - develop    # Auto-deploy to dev
      - staging    # Auto-deploy to staging
      - main       # Auto-deploy to production

jobs:
  # ========================================
  # AMBIENTE: DESARROLLO
  # ========================================
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    uses: YOUR-ORG/azure-workflow-actions/.github/workflows/deploy-function.yml@main  # ⚠️ CAMBIAR: YOUR-ORG por tu organización
    with:
      # ⚠️ CAMBIAR estos valores según tu proyecto:
      function-app-name: 'mi-function-dev'              # Nombre de tu Azure Function en dev
      resource-group: 'mi-rg-dev'                       # Resource Group de dev
      package-path: './mi-funcion'                      # Ruta a tu carpeta de función
      
      # ✅ Opcionales - ajusta según necesites:
      environment: 'dev'
      node-version: '18.x'                              # Cambia si usas otra versión
      run-tests: true
      enable-notifications: true
      create-release-on-success: true

  # ========================================
  # AMBIENTE: STAGING
  # ========================================
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    uses: YOUR-ORG/azure-workflow-actions/.github/workflows/deploy-function.yml@main  # ⚠️ CAMBIAR: YOUR-ORG por tu organización
    with:
      # ⚠️ CAMBIAR estos valores según tu proyecto:
      function-app-name: 'mi-function-staging'
      resource-group: 'mi-rg-staging'
      package-path: './mi-funcion'
      
      # ✅ Opcionales - ajusta según necesites:
      environment: 'staging'
      node-version: '18.x'
      run-tests: true
      enable-notifications: true
      slot-name: 'staging'                              # Deploy a slot de staging
      create-release-on-success: true

  # ========================================
  # AMBIENTE: PRODUCCIÓN
  # ========================================
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: YOUR-ORG/azure-workflow-actions/.github/workflows/deploy-function.yml@main  # ⚠️ CAMBIAR: YOUR-ORG por tu organización
    with:
      # ⚠️ CAMBIAR estos valores según tu proyecto:
      function-app-name: 'mi-function-prod'
      resource-group: 'mi-rg-prod'
      package-path: './mi-funcion'
      
      # ✅ Opcionales - ajusta según necesites:
      environment: 'prod'
      node-version: '18.x'
      run-tests: true
      enable-notifications: true
      create-release-on-success: true                   # Crea release oficial

# ============================================
# 💡 NOTAS:
# - NO necesitas configurar secrets en tu repo
# - Todos los secrets están en azure-workflow-actions
# - Puedes eliminar ambientes que no uses (dev/staging/prod)
# ============================================
